name: Run quality tasks for python projects
on:
  workflow_call:
    inputs:
      python-version:
        description: "The python version to use for executing the quality tasks."
        required: true
        type: string
      python-package-path:
        description: "Path of the python package under quality test."
        required: true
        type: string
      unit-test-file-pattern:
        description: "The pattern to search for unit test files."
        required: false
        type: string
        default: "'test*.py'"
      aws-account-id:
        description: "The aws account id used for login."
        type: string
        required: true
      aws-region:
        description: "AWS region of the codeartifact domain."
        type: string
        required: true
      codeartifact-domain:
        description: "Domain of the aws codeartifact repository."
        type: string
        required: true
      codeartifact-repository:
        description: "The aws codeartifact repository."
        type: string
        required: true
      use-tox:
        description: "Use tox to run quality tasks"
        required: false
        type: string
        default: false

    secrets:
      aws-access-key-id:
        description: "The aws access key id used for login."
        required: true
      aws-secret-access-key:
        description: "The aws secret access key used for login."
        required: true
      role-external-id:
        description: "The external ID of the role to assume."
        required: true
      ci-token:
        description: "The ci token to use."
        required: false
      sonar-token:
        description: "The token to use for sonarcloud."
        required: false

jobs:
  format:
    name: "Check Black Formatting"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: psf/black@stable

  test:
    name: "Test Python Package"
    runs-on: ubuntu-20.04
    needs: [format]
    timeout-minutes: 60
    if: ${{ inputs.use-tox == 'false'}}
    steps:
      - uses: actions/checkout@v2

      - name: "Setup Python"
        uses: actions/setup-python@v2
        with:
          python-version: ${{ inputs.python-version }}

      - name: "Configure AWS Credentials"
        uses: kraussmaffei/actions/configure-aws-credentials@main
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          role-to-assume: arn:aws:iam::${{ inputs.aws-account-id }}:role/PythonPackageIndexCodeartifactReadWrite
          role-external-id: ${{ secrets.role-external-id }}
          role-skip-session-tagging: true
          mask-aws-account-id: false
          aws-region: ${{ inputs.aws-region }}

      - name: "CodeArtifact login (pip)"
        uses: kraussmaffei/aws-tools-login@main
        with:
          account: ${{ inputs.aws-account-id }}
          region: ${{ inputs.aws-region }}
          aws-tool: "codeartifact-pip"
          codeartifact-domain: ${{ inputs.codeartifact-domain }}
          codeartifact-repository: ${{ inputs.codeartifact-repository }}

      - name: Install required tools
        shell: bash
        run: |
          pip install coverage flake8
          pip install .[test-dependencies]

      - name: Running flake8 linter...
        shell: bash
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 ./${{ inputs.python-package-path }} --count --select=E9,F63,F7,F82 --builtins="_" --show-source --statistics

          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 ./${{ inputs.python-package-path }} --count --exit-zero --max-complexity=10 --builtins="_" --max-line-length=127 --statistics

      - name: Running coverage calculation...
        id: coverage-calculator
        shell: bash
        run: |
          coverage run --source=${{ inputs.python-package-path }} -m unittest discover -s tests -p ${{ inputs.unit-test-file-pattern }}
          echo "::set-output name=total-coverage::$(coverage report -m | grep -o -E 'TOTAL.+ ([0-9]{1,3}%)' | grep -o -E '([0-9]{1,3}%)' | grep -o -E '([0-9]+)')"
          coverage xml -o ./coverage-reports/coverage.xml

      - name: SonarCloud Scan
        if: ${{ steps.use-sonarcloud.outputs.use-sonarcloud == 'true'}}
        uses: sonarsource/sonarcloud-github-action@v1.6
        env:
          GITHUB_TOKEN: ${{ secrets.ci-token }}
          SONAR_TOKEN: ${{ secrets.sonar-token }}

  test-using-tox:
    name: "Test Python Package using tox"
    runs-on: ubuntu-20.04
    needs: [format]
    timeout-minutes: 60
    if: ${{ inputs.use-tox == 'true'}}
    env:
      PYTHON_PACKAGE_PATH: ${{ inputs.python-package-path }}
      UNIT_TEST_FILE_PATTERN: ${{ inputs.unit-test-file-pattern }}
      COVERAGE_REPORT_OUTPUT: "./coverage-reports/coverage.xml"
    steps:
      - uses: actions/checkout@v2

      - name: "Setup Python"
        uses: actions/setup-python@v2
        with:
          python-version: ${{ inputs.python-version }}

      - name: "Configure AWS Credentials"
        uses: kraussmaffei/actions/configure-aws-credentials@main
        with:
          aws-access-key-id: ${{ secrets.aws-access-key-id }}
          aws-secret-access-key: ${{ secrets.aws-secret-access-key }}
          role-to-assume: arn:aws:iam::${{ inputs.aws-account-id }}:role/PythonPackageIndexCodeartifactReadWrite
          role-external-id: ${{ secrets.role-external-id }}
          role-skip-session-tagging: true
          mask-aws-account-id: false
          aws-region: ${{ inputs.aws-region }}

      - name: "CodeArtifact login (pip)"
        uses: kraussmaffei/aws-tools-login@main
        with:
          account: ${{ inputs.aws-account-id }}
          region: ${{ inputs.aws-region }}
          aws-tool: "codeartifact-pip"
          codeartifact-domain: ${{ inputs.codeartifact-domain }}
          codeartifact-repository: ${{ inputs.codeartifact-repository }}

      - name: Install required tools
        shell: bash
        run: |
          pip install tox

      - name: Run tox
        shell: bash
        run: |
          tox

      - name: SonarCloud Scan
        if: ${{ steps.use-sonarcloud.outputs.use-sonarcloud == 'true'}}
        uses: sonarsource/sonarcloud-github-action@v1.6
        env:
          GITHUB_TOKEN: ${{ secrets.ci-token }}
          SONAR_TOKEN: ${{ secrets.sonar-token }}
